

# This file was *autogenerated* from the file gen_test_vectors.sage
from sage.all_cmdline import *   # import sage library

_sage_const_256 = Integer(256); _sage_const_17 = Integer(17); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_0 = Integer(0)
import argparse
import random
import os
from FIOS import FIOS

if __name__ == "__main__":
	parser = argparse.ArgumentParser(description = "Generate test FIOS test vectors.")
	parser.add_argument("-w", metavar = "WIDTH", type = int, default = _sage_const_256 ,
						help = "Bit-width of the test vectors.")
	parser.add_argument("-n", metavar = "NUMBER", type = int, default = None,
						help = "Number of test vectors.")
	parser.add_argument ("-ww", metavar = "WORD WIDTH", type = int, default = _sage_const_17 ,
	                    help = "Word width.")
	parser.add_argument("--name", metavar = "FILE NAME", type = str, default = None,
						help = "Name of test vector file. Default : sim_<WIDTH>")
						
	args = parser.parse_args()

	w = args.ww

	WIDTH = args.w

	if args.n is not None:
		test_vectors_nb = args.n
	else:
		test_vectors_nb = _sage_const_1 

	if args.name is not None:
		filename = args.name + ".txt"
	else:
		filename = "sim_" + str(WIDTH) + ".txt"
		

	filename = os.path.abspath(os.path.dirname(__file__)) + "/TEST_VECTORS/TXT/" + filename
    
	with open(filename, "w") as test_file:

		for i in range(test_vectors_nb):
		
			n = random_prime(_sage_const_2 **WIDTH, False, _sage_const_2 **(WIDTH-_sage_const_1 ))
			
			a = random.randrange(_sage_const_2 **(WIDTH-_sage_const_1 ), n)
			b = random.randrange(_sage_const_2 **(WIDTH-_sage_const_1 ), n)
		
		
			res_arr, n_prime_0 = FIOS(n, a, b, w = w, WIDTH = WIDTH)
			
			res = _sage_const_0 
		
			for j in range(len(res_arr)):
				
				res += res_arr[j] << (j*w)
			
			test_file.write("n\n" + hex(n)[_sage_const_2 :] + "\n\nn_prime_0\n" + hex(n_prime_0)[_sage_const_2 :]
							+ "\n\na\n" + hex(a)[_sage_const_2 :] + "\n\nb\n" + hex(b)[_sage_const_2 :] + "\n\nres\n"
							+ hex(res)[_sage_const_2 :] + "\n\n\n")

